//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartItemId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
